<?php

namespace Jsadways\LaravelSDK\Console\Commands\MakeClass;

class MakeClassRepository extends BaseMakeClassCommand
{
    protected $name = 'make:sdk-repository';
    protected $description = 'Create sdk repository class';
    protected string $stub_path = 'repositories/ClassRepository';
    protected string $target_path = '\Repositories';

    public function handle(): ?bool
    {
        $dto_base_name = preg_replace("/Repository$/", "Dto", $this->getNameInput());

        $this->call("make:sdk-repository-dto",[
            'name' => "Create".$dto_base_name
        ]);
        $this->call("make:sdk-repository-dto",[
            'name' => "Update".$dto_base_name
        ]);

        return parent::handle(); // TODO: Change the autogenerated stub
    }
}
