<?php

namespace Jsadways\LaravelSDK\Console\Commands\MakeClass;

use Jsadways\LaravelSDK\Console\Commands\Traits\table_method;

class MakeClassModel extends BaseMakeClassCommand
{
    use table_method;

    protected $name = 'make:sdk-model';
    protected $description = 'Create sdk model class';
    protected string $stub_path = 'models/ClassModel';
    protected string $target_path = '\Models';
    protected array $replace_tags = [];

    public function handle(): ?bool
    {
        $model_name = strtolower($this->argument('name'));
        $this->replace_tags = ['table_name'=>$model_name];

        //get columns
        $columns = $this->_get_table_columns($model_name);
        if($columns){
            //handle column schema
            $schema_array = $this->_handle_schema($columns);
            $schema = var_export($schema_array,true);
            $this->replace_tags['schema'] = $this->_array_tag_replace($schema);
        }

        return parent::handle(); // TODO: Change the autogenerated stub
    }

    protected function _handle_schema(array $columns): array
    {
        $schema_array = [];
        foreach ($columns as $column){
            if(($validate_type = $this->_column_type_match($column['Type'])) && !$this->_column_ignored($column['Field'])){
                $required = $this->_column_need_require($column['Null']);
                $schema_array[$column['Field']] = "{$required}|{$validate_type}";
            }
        }

        return $schema_array;
    }

    protected function _column_type_match(string $type): bool|string
    {
        return match (true){
            str_ends_with($type,'int'),str_ends_with($type,'int unsigned'),str_ends_with($type,'int signed') => 'integer',
            str_starts_with($type,"tinyint(1)"),str_starts_with($type,"tinyint(2)") => 'boolean',
            str_starts_with($type,"varchar") => (preg_match('/\d+/',$type,$matches)) ? 'string|max:'.$matches[0]:'string',
            str_starts_with($type,"longtext") => 'array',
            str_ends_with($type,"text") => 'string',
            str_starts_with($type,"date") => 'date',
            default => false
        };
    }

    protected function _column_need_require(string $column_null): string
    {
        return ($column_null === 'NO') ?'required' : 'nullable';
    }

    protected function _column_ignored(string $column_name):bool
    {
        return match($column_name){
            'id' => true,
            default => false
        };
    }

    protected function _array_tag_replace(string $schema_array): array|string
    {
        $schema_array = str_replace('array (','[',$schema_array);
        return str_replace(')',']',$schema_array);
    }
}
