<?php

namespace Jsadways\LaravelSDK\Console\Commands\OLD\MakeClass;

class MakeClassControllerContract extends BaseMakeClassCommand
{
    protected $name = 'make:sdk-controller-contract';
    protected $description = 'Create sdk controller contract class';
    protected string $stub_path = 'http/ClassControllerContract';
    protected string $base_target_path = '\Core\\Controllers';
    protected string $target_path = '';

    public function handle(): ?bool
    {
        $controller_name = preg_replace("/Contract$/", "", $this->argument('name'));
        $this->target_path = $this->base_target_path . '\\' . $controller_name;

        return parent::handle(); // TODO: Change the autogenerated stub
    }
}
