<?php

namespace Jsadways\LaravelSDK\Console\Commands\OLD\MakeClass;

class MakeClassController extends BaseMakeClassCommand
{
    protected $name = 'make:sdk-controller';
    protected $description = 'Create sdk controller class';
    protected string $stub_path = 'http/ClassController';
    protected string $target_path = '\Http\\Controllers';
    protected string $dir = '';
    protected array $replace_tags = [];

    public function handle(): ?bool
    {
        $controller_name = $this->_separate_dir_name($this->getNameInput());
        $contract_name = preg_replace("/Controller$/", "Contract", $controller_name);
        $table_name = preg_replace("/Controller$/", "", $controller_name);

        $this->replace_tags['use_string'] = "use App\\Core\\Controllers\\{$table_name}\\{$contract_name};\n";
        $this->replace_tags['contract'] = $contract_name;
        if($this->dir !== ''){
            $this->replace_tags['use_string'] = $this->replace_tags['use_string']."use App\\Http\\Controllers\\Controller;";
        }
        $this->call('make:sdk-controller-contract',[
            'name' => $contract_name
        ]);

        return parent::handle(); // TODO: Change the autogenerated stub
    }

    protected function _separate_dir_name($name):string
    {
        #api/name or web/name or name
        $parts = explode('/',$name);
        if(count($parts) === 2){
            $this->dir = strtolower($parts[0]);
            $name = $parts[1];
        }

        return $name;
    }
}
